SUPER_CONFIG_PATH: ./configs/r50_deformable_detr_motip_dancetrack.yaml

DATASETS: [BFT]
DATASET_SPLITS: [train]
INFERENCE_DATASET: BFT
INFERENCE_SPLIT: test

DETR_PRETRAIN: ./pretrains/r50_deformable_detr_coco_bft.pth
DETR_DEFAULT_CLASS_IDX: 15    # class 15 is "bird" in COCO

SAMPLE_LENGTHS: [20, ]
REL_PE_LENGTH: 20
MISS_TOLERANCE: 20

EPOCHS: 22
SCHEDULER_MILESTONES: [16, 20, ]
LR_WARMUP_EPOCHS: 2
SAVE_CHECKPOINT_PER_EPOCH: 2

USE_DECODER_CHECKPOINT: False